language: node_js
dist: trusty
sudo: required
branches:
  only:
    - master
node_js:
  - "node"
  - "8"
  - "7"
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - npm run lint
script:
  - npm test
after_success:
  - npm run coverage
